version: '3.3'
services:
  web:
    build: flask
    expose:
      - "5000"
    #    ports:
    # - "5000:5000"
    #
  proxy:
    build: haproxy
    depends_on:
      - web
    ports:
      - "80:80"
      - "9101:9101"
      - "8404:8404"

  monitor:
    #image: "prom/prometheus"
    build: prometheus
    # root user permissions on host for this container to mount volume in root folder
    user: "0:0"
    depends_on:
      - web
      - proxy
    ports:
      - "9090:9090"
    links:
      - "proxy:haproxy"
    volumes:
      - ./prometheus:/prometheus
        #- ./data/prometheus:/data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
        #- '--storage.tsdb.path=/data'
        #
  graph:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - monitor
    user: "0:0"
    volumes:
      - ./grafana/data:/var/lib/grafana

