version: '3.3'
services:
  db:
    build: mysql/mysql-docker/5.7/
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=testpassword
    user: "0:0"
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      mynetwork:
        aliases:
          - my_mysql_node
        ipv4_address: 172.18.0.2
        #ipv6_address: 2001:3984:3989::10
  web:
    build: flask
    depends_on:
      - db
    # expose publishes only in network
    expose:
      - "5000"
    # ports is used to publish to host
    #    ports:
    # - "5000:5000"

  proxy:
    build: haproxy
    depends_on:
      - web
    ports:
      - "80:80"
      - "9101:9101"
      - "8404:8404"
    networks:
      mynetwork:
        aliases:
          - haproxy

  monitor:
    #image: "prom/prometheus"
    build: prometheus
    # root user permissions on host for this container to mount volume in root folder
    user: "0:0"
    depends_on:
      - web
      - proxy
    ports:
      - "9090:9090"
    links:
      - "proxy:haproxy"
    volumes:
      - ./prometheus:/prometheus
        #- ./data/prometheus:/data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
        #- '--storage.tsdb.path=/data'
        #
  graph:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - monitor
    user: "0:0"
    volumes:
      - ./grafana/data:/var/lib/grafana

  dbadmin:
    image: phpmyadmin/phpmyadmin
    expose:
      - "8080"
    environment:
      - PMA_HOST=my_mysql_node
    networks:
      mynetwork:
        ipv4_address: 172.18.0.8
    depends_on:
      - db

networks:
  mynetwork:
    external:
      name: docker_default
    #ipam:
      #driver: default
      #config:
        #- subnet: "172.88.92.0/24"
        #- subnet: "2001:3984:3989::/64"

