apiVersion: v1
kind: Secret
metadata:
  name: kisp-secrets
type: Opaque
stringData:
    KISP_ADMIN_PASSWORD: "testpassword"
    MYSQL_ROOT_PASSWORD: "testmysqlpass"
    MYSQL_ROOT_HOST: "10.74.224.3"
