apiVersion: v1
kind: PersistentVolume
metadata:
          name: test-persistent-volume
spec:
        accessModes:
        - ReadWriteOnce
        capacity:
                storage: 10Gi
        persistentVolumeReclaimPolicy: Retain
        gcePersistentDisk:
                pdName: test-persistent-disk #This disk was created in gcloud
